### ISSUE TITLE
Add a Quick Start section to the main README.md

### ISSUE THREAD

**Issue by maxidor** [kamax-matrix/matrix-java-sdk#12]
Describe how to perform basic actions with the SDK:
- [x] Login with password
- [x] List joined rooms
- [x] Join room
- [x] Leave room
- [x] Send message to room
- [x] Handle events
  - [x] Incoming message from room

**Comment by athlordJojo** [comment]
This would be awesome. 
Because i still struggle to find a way to listen on new events/messages to a room...

**Comment by maxidor** [comment]
@athlordJojo We haven't so far because we keep changing the way things are done, as we improve the usage (hence the milestone for v0.1)

But the [Send'n'Leave bot](https://github.com/kamax-matrix/matrix-send-n-leave-bot) uses the SDK and shows a [very simple use case](https://github.com/kamax-matrix/matrix-send-n-leave-bot/blob/master/src/main/java/io/kamax/matrix/bots/send_n_leave/SendNLeaveBot.java#L68). This is the best starting point we have right now.

**Comment by maxidor** [comment]
Fixed in 74e051384490da25e2a20e34aa19a46ef5cd08c7 while we perform our final refactoring
