### ISSUE TITLE
Add optional fileName parameter to MatrixHttpClient.putMedia(File data, String type).

### ISSUE THREAD

**Issue by chresan** [kamax-matrix/matrix-java-sdk#62]
There is a currently a method defined for uploading files and specifying the content-type:
`MatrixHttpClient.putMedia(File data, String type)`.

There should be an additional method which accepts a filename parameter:
`MatrixHttpClient.putMedia(File data, String type, String filename)`

The specification defines the URL query parameter `filename`. 
See https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-media-r0-upload

The m.room.message with message type m.image specifies only the name that is displayed. However when downloading a file, the matrix client gets a random filename such as `AgTxPeyqwuCUpoyPjAgBcVxH.png`

**Comment by maxidor** [comment]
Omission indeed, will fix
